<div class="large-8 medium-10 small-12 columns panel" style="margin-top: 20px; /* for allowing space below navigation bar */">
    <h2>Pol&iacute;tica de privacidade para Demi-Mot</h2>
    <p>Todas as suas informa&ccedil;&otilde;es pessoais recolhidas, ser&atilde;o usadas para o ajudar a tornar a sua visita no nosso site o mais produtiva e agrad&aacute;vel poss&iacute;vel.</p>
    <p>A garantia da confidencialidade dos dados pessoais dos utilizadores do nosso site &eacute; importante para o Teste.</p>
    <p>Todas as informa&ccedil;&otilde;es pessoais relativas a membros, assinantes, clientes ou visitantes que usem o Teste ser&atilde;o tratadas em concord&acirc;ncia com a Lei da Prote&ccedil;&atilde;o de Dados Pessoais de 26 de outubro de 1998 (Lei n.&ordm; 67/98).</p>
    <p>A informa&ccedil;&atilde;o pessoal recolhida pode incluir o seu nome, e-mail, n&uacute;mero de telefone e/ou telem&oacute;vel, morada, data de nascimento e/ou outros.</p>
    <p>O uso do Teste pressup&otilde;e a aceita&ccedil;&atilde;o deste Acordo de privacidade. A equipa do Teste reserva-se ao direito de alterar este acordo sem aviso pr&eacute;vio. Deste modo, recomendamos que consulte a nossa pol&iacute;tica de privacidade com regularidade de forma a estar sempre atualizado.</p>
    <h2>Os an&uacute;ncios</h2>
    <p>Tal como outros websites, coletamos e utilizamos informa&ccedil;&atilde;o contida nos an&uacute;ncios. A informa&ccedil;&atilde;o contida nos an&uacute;ncios, inclui o seu endere&ccedil;o IP (Internet Protocol), o seu ISP (Internet Service Provider, como o Sapo, Clix, ou outro), o browser que utilizou ao visitar o nosso website (como o Internet Explorer ou o Firefox), o tempo da sua visita e que p&aacute;ginas visitou dentro do nosso website.</p>
    <h2>Cookie DoubleClick Dart</h2>
    <p>O Google, como fornecedor de terceiros, utiliza cookies para exibir an&uacute;ncios no nosso website;</p>
    <p>Com o cookie DART, o Google pode exibir an&uacute;ncios com base nas visitas que o leitor fez a outros websites na Internet;</p>
    <p>Os utilizadores podem desativar o cookie DART visitando a Pol&iacute;tica de privacidade da rede de conte&uacute;do e dos an&uacute;ncios do Google.</p>
    <h2>Os Cookies e Web Beacons</h2>
    <p>Utilizamos cookies para armazenar informa&ccedil;&atilde;o, tais como as suas prefer&ecirc;ncias pessoas quando visita o nosso website. Isto poder&aacute; incluir um simples popup, ou uma liga&ccedil;&atilde;o em v&aacute;rios servi&ccedil;os que providenciamos, tais como f&oacute;runs.</p>
    <p>Em adi&ccedil;&atilde;o tamb&eacute;m utilizamos publicidade de terceiros no nosso website para suportar os custos de manuten&ccedil;&atilde;o. Alguns destes publicit&aacute;rios, poder&atilde;o utilizar tecnologias como os cookies e/ou web beacons quando publicitam no nosso website, o que far&aacute; com que esses publicit&aacute;rios (como o Google atrav&eacute;s do Google AdSense) tamb&eacute;m recebam a sua informa&ccedil;&atilde;o pessoal, como o endere&ccedil;o IP, o seu ISP, o seu browser, etc. Esta fun&ccedil;&atilde;o &eacute; geralmente utilizada para geotargeting (mostrar publicidade de Lisboa apenas aos leitores oriundos de Lisboa por ex.) ou apresentar publicidade direcionada a um tipo de utilizador (como mostrar publicidade de restaurante a um utilizador que visita sites de culin&aacute;ria regularmente, por ex.).</p>
    <p>Voc&ecirc; det&eacute;m o poder de desligar os seus cookies, nas op&ccedil;&otilde;es do seu browser, ou efetuando altera&ccedil;&otilde;es nas ferramentas de programas Anti-Virus, como o Norton Internet Security. No entanto, isso poder&aacute; alterar a forma como interage com o nosso website, ou outros websites. Isso poder&aacute; afetar ou n&atilde;o permitir que fa&ccedil;a logins em programas, sites ou f&oacute;runs da nossa e de outras redes.</p>
    <h2>Liga&ccedil;&otilde;es a Sites de terceiros</h2>
    <p>O Teste possui liga&ccedil;&otilde;es para outros sites, os quais, a nosso ver, podem conter informa&ccedil;&otilde;es / ferramentas &uacute;teis para os nossos visitantes. A nossa pol&iacute;tica de privacidade n&atilde;o &eacute; aplicada a sites de terceiros, pelo que, caso visite outro site a partir do nosso dever&aacute; ler a politica de privacidade do mesmo.</p>
    <p>N&atilde;o nos responsabilizamos pela pol&iacute;tica de privacidade ou conte&uacute;do presente nesses mesmos sites.</p>
</div>